### ISSUE TITLE
Future option: feed keystrokes to command?

### ISSUE THREAD

**Issue by emendelson** [cracyc/msdos-player#3]
For batch operations, it would be very useful to have a -k option that would type keystrokes after the program specified by the command is launched. So if I enter 

MSDOS someExe.exe

and someExe.exe prompts for input that cannot be specified on a command line, the -k option would type those keystrokes.

This would be useful for applications like ConvertPerfect that prompt for a password when converting an encrypted file but won't let you specify it on the command line.

I know I'm asking a lot!

**Comment by cracyc** [comment]
https://github.com/cracyc/msdos-player/commit/3fb8da96e9ea04b3efb4f788759c0a9df538b29b

It's -a rather than -k.   It also supports \n and \t c escapes for newline and tab and the command can be quoted for spaces.  It only works with programs that use the bios or dos for keyboard reading (which should be most non-game software).

**Comment by emendelson** [comment]
Amazingly fast - thank you! I'll build this weekend.
